[project]
name = "discord-vid"
version = "0.1.0"
requires-python = "==3.14.*"
dependencies = [
    "requests~=2.28",
    "pyinstaller>=6.16",
    "pyzmq>=26",
    "tkinterdnd2~=0.3",
    "pydantic~=2.3",
    "wmi>=1.5.1",
    "tzdata>=2026.3",
]

[dependency-groups]
dev = [
    "pre-commit>=4.3.0",
    "ruff>=0.16.4",
]

[tool.ruff.lint]
select = ["E", "F", "W", "C90", "I", "N", "UP", "B"]

[tool.ruff.format]
line-ending = "lf"
